%FSR_demo1 - CRONE Toolbox
% 
% Demo file for Fractional System Representations
%
% Copyright (c) CRONE -	18/11/2014
% Last revision: 29/10/2021

clc
disp(' ')
disp(' ')
disp('            System Identification for Fractional Order Model')
disp('                     with the CRONE toolbox')
disp('               --------------------------------------')
disp(' ')

disp('   This demo will illustrate the use of the CRONE Toolbox')
disp('   for a thermal application: the heat flux flowing on an aluminium rod.');
disp('   It has been theoretically proven that the model linking the')
disp('   temperature at a given point of a rod to a heat flux injected at')
disp('   one end of the rod can be modeled by a fractional transfer function.')
disp(' ')
disp('   Hit any key to continue')
pause

clc
echo on

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   Identification data 
%   
%   A real experiment has been carried out with an aluminium rod. A long 
%   aluminum rod heated by a resistor at one end is considered in the 
%   experiment. The input signal is a thermal flux generated by a resistor 
%   glued at one end and the output signal is he temperature of the rod 
%   measured at a distance x = 0.5 cm from the heated end using a platinum 
%   probe and an amplifier with a quantification error of 0.125°. To ensure 
%   a unidirectional heat transfer, the entire surface of the rod is 
%   insulated. A delay of 4 samples (2 s) is observed between the output 
%   and the input. The input density flux and the output temperature are 
%   pretreated to eliminate the constant parts and the delay.
%   The input and output data have been saved in the following file
    path=which('CRONE_demos');
    eval (['load ' '''' path(1:end-13) 'ThermalRod.mat' ''''])
    
%   It is then required to put the data as an iddata object 
%   Here only the first output is taken
    data = iddata(y(:,1),u,Ts);
    
%   Since the aluminum rod reaches a steady state temperature, it is not 
%   perfectly insulated. Consequently, there is no reason to have a 
%   commensurate order of 0.5 nor to have an integrator as in the physical  
%   model. A frac_tf object sys_init is created in order to initialize the
%   identification routines. This object will help to specify the number of
%   parameter to be identified (coefficients and differentiation orders).
    nu=0.6;
    sys_init = frac_tf(1, frac_poly_exp([1 1 1], ...
    [2*nu nu 0]), 'N', 24, 'band', [1e-5 5e1])

%   Hit any key
    pause
    clc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   OE methods

%   When calling the oe routine of the CRONE toolbox, the first argument 
%   must be a frac lti object, otherwise the oe routine of System 
%   Identification Toolbox is executed. The second argument is an iddata 
%   object of the System Identification Toolbox. The oe routine calls 
%   lsqnonlin routine of Optimisation toolbox and the third argument allows 
%   to set optimization options used by the latter function. Finally, the 
%   last argument allows choosing one of the four options offered:

%   - 'coef' for coefficient estimation:
    sys_oe_coef = oe(sys_init, data,[],'Coefficients');
    get(sys_oe_coef,'sys')

%   Hit any key
    pause
    clc
%   - 'comm' for coefficient and the commensurate order estimation:
    sys_oe_comm = oe(sys_oe_coef, data,[],'Commensurate');
    get(sys_oe_comm,'sys')

%   Hit any key
    pause
    clc
%   - 'all' for coefficient and differentiation order estimation:
    sys_oe_all = oe(sys_oe_comm, data,[],'All');
    get(sys_oe_all,'sys')

    %   Hit any key
    pause
    clc
%   A comparison between all three outputs is done in the following lines.
    t = (0: (length(u)-1))'*Ts;
    figure, 
    subplot(211),plot(t,y,'b',...
        t,lsim(sys_oe_coef,u,t),'r--',...
        t,lsim(sys_oe_comm,u,t),'g-.',...
        t,lsim(sys_oe_all,u,t),'m')
    echo off
    legend('True system','OE with coef. estimation',... 
        'OE with coef. and comm. order estimation',...
        'OE with coef and all order estimation')
    % axis([0 600 -1.5 1.5])
    echo on
    subplot(212),plot(t,y-lsim(sys_oe_coef,u,t),...
        'r--',t,y-lsim(sys_oe_comm,u,t),'g-.',t,...
        y-lsim(sys_oe_all,u,t),'m')
    echo off
    legend('Error function for coef. estimation',... 
        'Error function for coef. and comm. order estimation ',...
        'Error function for coef and all order estimation')

%    echo on
%   Hit any key
%    pause
%    clc 
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%    
% %   OOSRIVCF methods
% 
% %   When calling the oosrivcf routine of the CRONE toolbox, the first 
% %   argument must be a frac lti object. The second argument is an iddata 
% %   object of the System Identification Toolbox. The third argument allows 
% %   choosing one of the three options offered, just as in the oe routine.
% 
% %   - 'coef' for coefficient estimation:
%     sys_srivcf_coef = oosrivcf(sys_init,data,'Coefficients', [20, 1e-4])
% 
% %   Hit any key
%     pause
% 
% %   - 'comm' for coefficient and the commensurate order estimation:
%     sys_oosrivcf_com = oosrivcf(sys_srivcf_coef,data,'Commensurate', [200, 1e-4])
%     
%     %   Hit any key
%     pause
%    
%     
% %   - 'all' for coefficient and differentiation order estimation:
%     sys_oosrivcf_all = oosrivcf(sys_oosrivcf_com,data,'all', [200, 1e-4])
% 
%     %   Hit any key
%     pause
%     %   A comparison between all three outputs is done in the following lines.
% 
%     figure, 
%     subplot(211),plot(t,y,'b',...
%         t,lsim(sys_srivcf_coef,u,t),'r--',...
%         t,lsim(sys_oosrivcf_com,u,t),'g-.',...
%         t,lsim(sys_oosrivcf_all,u,t),'m')
%     echo off
%     legend('True system','srivcf with coef. estimation',... 
%         'srivcf with coef. and comm. order estimation',...
%         'srivcf with coef and all order estimation')
%     % axis([0 600 -1.5 1.5])
%     echo on
%     subplot(212), plot(t,y-lsim(sys_srivcf_coef,u,t),'r--',...
%         t,y-lsim(sys_oosrivcf_com,u,t),'g-.',...
%         t,y-lsim(sys_oosrivcf_all,u,t),'m')
%     legend('Error function for coef. estimation',... 
%         'Error function for coef. and comm. order estimation ',...
%         'Error function for coef and all order estimation')
% 
% %   Hit any key
%     pause    
%     
% echo off
% close all
% clc

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% v0.1 Victor   02/02/2015  Creation de la fonction
% v0.2 Malti    19/10/2015  Correction de qlq bugs vers la fin et appel au
%               bon fichier .mat ==> Données d'Automatica.
% v2.0 Loo      29/10/2021  Corrections des options et affichages des sys